# Generated by Django 2.2.4 on 2019-09-04 19:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_auto_20190903_1347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='semester',
            name='year',
            field=models.DateField(default=2019, validators=[django.core.validators.MinValueValidator(2015), django.core.validators.MaxValueValidator(2021)], verbose_name='year'),
        ),
        migrations.AddConstraint(
            model_name='semester',
            constraint=models.UniqueConstraint(fields=('season', 'year'), name='semester'),
        ),
    ]
