# Generated by Django 2.2.4 on 2019-09-04 19:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_auto_20190904_1902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='semester',
            name='year',
            field=models.IntegerField(default=2019, validators=[django.core.validators.MinValueValidator(2015), django.core.validators.MaxValueValidator(2021)], verbose_name='year'),
        ),
    ]
