# Generated by Django 2.2.4 on 2019-09-13 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0006_attendance'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='date',
            field=models.DateTimeField(null=True),
        ),
    ]
