# Generated by Django 2.2.4 on 2019-09-13 18:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0007_classroom_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='credits',
            field=models.IntegerField(default=3, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AddField(
            model_name='classroom',
            name='end_time',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='classroom',
            name='start_time',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
