# Generated by Django 2.2.4 on 2019-09-21 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0013_auto_20190918_1452'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classroom',
            name='credits',
        ),
        migrations.RemoveField(
            model_name='classroom',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='classroom',
            name='start_time',
        ),
    ]
