# Generated by Django 2.2.4 on 2019-10-08 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0016_auto_20190930_1758'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='upload',
            field=models.FileField(default=1, upload_to='uploads/%Y/%m/%d/'),
            preserve_default=False,
        ),
    ]
