# Generated by Django 2.2.4 on 2019-10-08 19:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0017_attendance_upload'),
    ]

    operations = [
        migrations.CreateModel(
            name='Performance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.PositiveIntegerField()),
                ('test', models.CharField(max_length=25)),
                ('date', models.DateField()),
                ('notes', models.CharField(blank=True, max_length=500)),
                ('upload', models.FileField(upload_to='uploads/%Y/%m/%d/')),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance', to='school.Classroom')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance', to='school.Student')),
            ],
        ),
    ]
