# Generated by Django 2.2.4 on 2019-10-13 15:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0019_remove_performance_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='performance',
            name='weight',
            field=models.DecimalField(decimal_places=2, default=0.25, max_digits=4),
        ),
        migrations.AlterField(
            model_name='performance',
            name='grade',
            field=models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)]),
        ),
    ]
