# Generated by Django 2.2.4 on 2019-10-13 15:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0020_auto_20191013_1521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='performance',
            name='grade',
            field=models.PositiveIntegerField(null=True, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='performance',
            name='weight',
            field=models.DecimalField(decimal_places=2, max_digits=4, null=True),
        ),
    ]
