# Generated by Django 2.2.4 on 2019-10-19 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0022_auto_20191013_1613'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='classroom',
        ),
        migrations.AddField(
            model_name='classroom',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Performance',
        ),
        migrations.DeleteModel(
            name='Test',
        ),
    ]
